version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: alpine
    versions:
    - 3.13.1
    - 3.13.2
    - 3.13.3
    - 3.13.4
  - dependency-name: golang
    versions:
    - 1.15.7.pre.alpine
    - 1.15.8.pre.alpine
    - 1.16.0.pre.alpine
    - 1.16.1.pre.alpine
    - 1.16.2.pre.alpine
- package-ecosystem: docker
  directory: "/docker/dev"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: golang
    versions:
    - 1.15.7.pre.alpine
    - 1.15.8.pre.alpine
    - 1.16.0.pre.alpine
    - 1.16.1.pre.alpine
    - 1.16.2.pre.alpine
